### ISSUE TITLE
Right click support with other mods

### ISSUE THREAD

**Issue by OnyxBerryBagel** [Courseplay/ClickToSwitch#9]
I'm having an issue with this mod working with the auto-drive mod. I saw in the recent changelog that there was "added support for auto-drive" but ever since I added auto-drive, the click-to-switch mod has been barely working. I have been using courseplay and click-to-switch with no problems. Once I added auto-drive, the keybind to pull up the mouse for auto-drive (middle click) seemed to conflict with the keybind for courseplay (right click). I have tried multiple keybind switches to get the mouse on my screen and the ability to swap into another vehicle. It seems that I can't turn off the keybind on courseplay and just use middle click for autodrive and use the mouse that appears to switch and vice versa with with removing the keybind on auto-drive and just using the right click on courseplay (which worked before I installed auto-drive). Any suggestions would be appreciated as I love all 3 mods and don't want to get rid of any of them. Maybe there's an optimal setup I'm missing in order to get them all to mesh together. Thanks for all you do!

**Comment by pixelinkmedia** [comment]
I get this same exact issue with Auto Drive. 
It works great as long as I don't install and use AD.

However, when I install and use right click, it doesn't allow me to enter another vehicle.

I have done a lot of tests trying to figure out why AD and Click to Switch conflicts
There are no key-bindings that are the same.

It seems to me the issue may have something to do with both mods sharing the same right-click (or Middle mouse button) thread of the game. But, I am only gestimating.

I really need Click to Switch to save me on so many tabs while trying to get to a vehicle.
That's why I am also interested in AD. To save me some pain in my hands of having to drive everywhere.

Anything you need, just let me know.

Thanks

**Comment by pixelinkmedia** [comment]
I have come to know that there was a fix for this and so I installed AD again and used to suggested way to doing it now.
Also, I learned that if you have AD's top bar of icons (record, save etc) buttons, it won't work.
Make sure to hid those icons by clicking on the exclamation button on bottom right of AD window.
